name: Deploy to S3 with Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: List files in infrastructure
      run: ls -la ./infrastructure

    - name: Initialize Terraform
      working-directory: ./infrastructure
      run: terraform init

    - name: Show Terraform plan
      working-directory: ./infrastructure
      run: terraform plan

    - name: Apply Terraform
      working-directory: ./infrastructure
      run: terraform apply -auto-approve

    - name: List HTML files for S3 sync
      run: ls -la ./html_files  # Убедитесь, что файлы, которые вы хотите загрузить, находятся здесь

    - name: Sync files to S3
      run: |
        aws s3 sync ./html_files s3://my-personal-website-bucket --acl public-read
